import { useEffect, useRef, useState } from 'react'
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom'
import { negocio, whatsapp } from '../data/negocio'
import { navegacion } from '../data/contenido'
import { servicios } from '../data/servicios'
import Logo from './Logo'
import { Arrow } from './UI'
export default function Layout() {
 const [open, setOpen] = useState(false)
 const [scroll, setScroll] = useState({ solid: false, hidden: false, floating: false })
 const last = useRef(0)
 const trigger = useRef<HTMLButtonElement>(null)
 const menu = useRef<HTMLDivElement>(null)
 const { pathname } = useLocation()
 useEffect(() => { const onScroll = () => { const y = window.scrollY; setScroll({ solid: y > 35, hidden: y > last.current && y > 220, floating: y > window.innerHeight * .7 }); last.current = y }; window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll) }, [])
 useEffect(() => { if (!open) return; const before = document.body.style.overflow; document.body.style.overflow = 'hidden'; menu.current?.querySelector<HTMLAnchorElement>('a')?.focus(); const key = (e: KeyboardEvent) => { if (e.key === 'Escape') { setOpen(false); trigger.current?.focus() } if (e.key === 'Tab') { const els = [trigger.current, ...Array.from(menu.current?.querySelectorAll<HTMLAnchorElement>('a') || [])].filter(Boolean) as HTMLElement[]; const index = els.indexOf(document.activeElement as HTMLElement); e.preventDefault(); els[(index + (e.shiftKey ? -1 : 1) + els.length) % els.length]?.focus() } }; document.addEventListener('keydown', key); return () => { document.body.style.overflow = before; document.removeEventListener('keydown', key) } }, [open])
 return <><a href="#contenido" className="skip-link">Ir al contenido</a><header className={`site-header ${scroll.solid || pathname !== '/' || open ? 'solid' : ''} ${scroll.hidden && !open ? 'hidden-header' : ''}`}><Link className="brand" to="/" aria-label="LAHL, inicio" onClick={() => setOpen(false)}><Logo/></Link><nav className="desktop-nav" aria-label="Principal">{navegacion.map(([label, to]) => <NavLink key={to} to={to}>{label}</NavLink>)}</nav><a className="header-quote" href={whatsapp()} target="_blank" rel="noreferrer">Cotizar <Arrow diagonal/></a><button ref={trigger} className={`menu-toggle ${open ? 'is-open' : ''}`} aria-label={open ? 'Cerrar menú' : 'Abrir menú'} aria-expanded={open} aria-controls="menu-completo" onClick={() => setOpen(!open)}><span/><span/></button></header>
 {open && <div className="menu-overlay" id="menu-completo" ref={menu} role="dialog" aria-modal="true" aria-label="Navegación"><p className="eyebrow">Explorá LAHL</p><nav>{navegacion.map(([label,to],i) => <Link key={to} to={to} onClick={() => setOpen(false)}><span>0{i+1}</span>{label}<Arrow diagonal/></Link>)}</nav><a href={`mailto:${negocio.correo}`}>{negocio.correo}</a></div>}
 <div {...(open ? { inert: '' } : {})}><main id="contenido" tabIndex={-1}><Outlet/></main><footer className="site-footer container"><div className="footer-top"><Link to="/" aria-label="LAHL, inicio"><Logo/></Link><h2>Tu próximo espacio<br/>empieza con una idea.</h2><a className="round-link" href={whatsapp()} target="_blank" rel="noreferrer" aria-label="Cotizar por WhatsApp"><Arrow diagonal/></a></div><div className="footer-grid"><p>{negocio.frase}</p><div><p className="eyebrow">Conversemos</p><a href={`tel:${negocio.tel}`}>{negocio.telefono}</a><a href={`mailto:${negocio.correo}`}>{negocio.correo}</a><p>{negocio.horario}<br/><small>Días de atención por confirmar</small></p></div><div><p className="eyebrow">Servicios</p>{servicios.map(s => <Link key={s.slug} to={`/servicios/${s.slug}`}>{s.nombre}</Link>)}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {negocio.marca} {negocio.subtitulo}</span><span>Propuesta de sitio · Imágenes conceptuales</span><a href="#contenido">Volver arriba ↑</a></div></footer></div>
 {scroll.floating && !open && <a className="whatsapp-float" href={whatsapp()} target="_blank" rel="noreferrer" aria-label="Conversar por WhatsApp"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4" aria-hidden="true"><path d="M20.5 11.8a8.5 8.5 0 0 1-12.6 7.5L3 21l1.6-5A8.5 8.5 0 1 1 20.5 11.8Z"/><path d="M8 7.5c-2 3 4.5 9 7.5 7l1-2-3-1-.7 1c-1.5-.5-2.6-1.7-3-3l1-.7-1-2Z"/></svg></a>}</>
}
